# Generated by Django 5.2 on 2025-04-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_passenger'),
        ('park', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_maintainer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_passenger',
        ),
        migrations.RemoveField(
            model_name='fleetmanager',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='service_region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_location', to='park.park'),
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
