# Generated by Django 5.2 on 2025-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_is_arrived_vehicle_is_departed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='trip_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
