# Generated by Django 5.2 on 2025-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('ONEWAY', 'One Way'), ('ROUND', 'Round Trip'), ('HOURLY', 'Hourly Rental'), ('DAILY', 'Daily Rental')], max_length=10)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_type', models.CharField(choices=[('HOME', 'Home Pickup'), ('PARK', 'Park Meeting')], max_length=10)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('adult_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateTimeField()),
                ('luggage_count', models.PositiveIntegerField()),
                ('need_entourage', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_time', models.DateTimeField(blank=True, null=True)),
                ('booking_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
