# Generated by Django 5.2 on 2025-04-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('park', '0001_initial'),
        ('useraccount', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.passenger'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='park.park'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='park.park'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
    ]
