# Generated by Django 5.2 on 2025-04-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Passenger',
            new_name='passenger',
        ),
    ]
