# Generated by Django 5.2 on 2025-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_passenger_booking_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='return_adult_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_children_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
